name: CI

on:
  pull_request:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-flake-check:
    name: nix flake check - ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Nix
        uses: samueldr/lix-gha-installer-action@f5e94192f565f53d84f41a056956dc0d3183b343 # 2026-04-08
        with:
          extra_nix_config: |
            allow-import-from-derivation = false

      - name: Run nix flake check
        run: nix flake check --no-update-lock-file --keep-going --print-build-logs
